'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCBeneficiaryProfileViewV1

    '''<summary>
    '''UCDonorHeaderV11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCDonorHeaderV11 As Global.DirectAid.UCDonorHeaderV1

    '''<summary>
    '''UCBeneficiaryHeaderV11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCBeneficiaryHeaderV11 As Global.DirectAid.UCBeneficiaryHeaderV1
End Class
