'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BeneficiaryReportSearch

    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''ASPxLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel12 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_ReportType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_ReportType As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel20 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_SortOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_SortOrder As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel13 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''application_status_stud_orp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents application_status_stud_orp As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel14 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxTextBox_OutboxNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox_OutboxNumber As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel4 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''status_date_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_date_From As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel5 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''status_date_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_date_To As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''allocation_date_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents allocation_date_from As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''allocation_date_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents allocation_date_to As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel21 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''DeAllocationDate_From control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeAllocationDate_From As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel22 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''DeAllocationDate_To control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeAllocationDate_To As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''applicant_dob_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applicant_dob_from As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel7 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''applicant_dob_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applicant_dob_to As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel11 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''overall_last_update_date_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents overall_last_update_date_from As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel15 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''overall_last_update_date_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents overall_last_update_date_to As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel6 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''applicant_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applicant_gender As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel8 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''donor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donor As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel9 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_Country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_Country As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel19 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''center_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents center_tab As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel10 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''applicant_nat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents applicant_nat As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel18 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''app_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents app_ser As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel16 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxTextBox_AllocationFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox_AllocationFrom As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel17 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxTextBox_AllocationTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox_AllocationTo As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_orphanage_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_orphanage_code As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''orphanage_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents orphanage_code As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel_stud_qualif_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_stud_qualif_type As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''stud_qualif_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stud_qualif_type As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel_school_reg_date_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_school_reg_date_from As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''school_reg_date_from control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_reg_date_from As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_school_reg_date_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_school_reg_date_to As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''school_reg_date_to control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_reg_date_to As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_section_opinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_section_opinion As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''section_opinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents section_opinion As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel23 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''donor_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donor_id As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel24 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''donor_namear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donor_namear As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxButton_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Print As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLoadingPanel1 As Global.DevExpress.Web.ASPxLoadingPanel

    '''<summary>
    '''ASPxCallback_Print control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback_Print As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''ASPxButton_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_New As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''EntityDataSource_system_report control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_system_report As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''ObjectDataSource_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ObjectDataSource_Status As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''EntityDataSource_nat_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_nat_tab As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EntityDataSource_stud_qualif_type_codes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_stud_qualif_type_codes As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EntityDataSource_center_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_center_tab As Global.System.Web.UI.WebControls.EntityDataSource
End Class
