<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="donor_search_form.aspx.vb" Inherits="DirectAid.donor_search_form" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <style type="text/css">
        .style1
        {
            height: 21px;
        }
        .style29
        {
            width: 738px;
            height: 125px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <table style="width: 100%; height: 31px;">
        <tr>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td class="style1">
            </td>
            <td class="style1">
            </td>
            <td class="style1">
            </td>
        </tr>
        <tr>
            <td class="style1" colspan="3">
                        <table border="1" cellspacing="1" dir="rtl" 
                            
                            style="margin: auto; padding: inherit; border: 1px solid #FFFFFF; width: 80%; line-height: normal; vertical-align: middle; table-layout: auto;" 
                            __designer:mapid="796">
                            <tr __designer:mapid="797">
                                <td class="style29" dir="rtl" style="border: 1px none #FFFFFF" 
                                    __designer:mapid="798">
                                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                                        AutoGenerateSelectButton="True" CellPadding="1" ForeColor="#333333" 
                                        GridLines="Vertical" Height="27px" HorizontalAlign="Center" Width="736px">
                                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                        <Columns>
                                            <asp:TemplateField HeaderText="رقم المتبرع"></asp:TemplateField>
                                            <asp:TemplateField HeaderText="اسم المتبرع"></asp:TemplateField>
                                        </Columns>
                                        <EditRowStyle BackColor="#999999" />
                                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="False" Font-Names="Tahoma" 
                                            Font-Size="7pt" ForeColor="White" Height="25px" />
                                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                                    </asp:GridView>
                                </td>
                            </tr>
                        </table>
                    </td>
        </tr>
    </table>
</asp:Content>
