'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class NewDonationsDetail

    '''<summary>
    '''lblDOnationCod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''CmbSearchId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmbSearchId As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''Btn_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Search As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxGridView_Target control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView_Target As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''EntityDataSource_donations_rates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_donations_rates As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EntityDataSource_nat_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_nat_tab As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''LinqServerModeDataSource_target control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinqServerModeDataSource_target As Global.DevExpress.Data.Linq.LinqServerModeDataSource

    '''<summary>
    '''LinqServerModeDataSource_source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinqServerModeDataSource_source As Global.DevExpress.Data.Linq.LinqServerModeDataSource

    '''<summary>
    '''DsSearchID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DsSearchID As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxButton_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Add As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Remove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Remove As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxGridView_Source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView_Source As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ASPxCallback_Add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback_Add As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''ASPxCallback_Remove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback_Remove As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''ASPxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLoadingPanel1 As Global.DevExpress.Web.ASPxLoadingPanel
End Class
