'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class orphans_health_file

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lnk_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_search As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_save As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnk_search_rtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_search_rtn As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_Get_Fayher_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_Get_Fayher_name As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label306 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label306 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_app_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_app_ser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label315 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label315 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_report_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_report_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''Label218 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label218 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_orphan_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_orphan_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chk_card_available control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_card_available As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Label162 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label162 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label307 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label307 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_health_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_health_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label163 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label163 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label308 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label308 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_hearing_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_hearing_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label164 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label164 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label311 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label311 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_eye_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_eye_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label165 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label165 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label309 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label309 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_psych_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_psych_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label166 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label166 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label310 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label310 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_general_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_general_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label167 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label167 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label312 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label312 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_surger_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_surger_status As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label214 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label214 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label314 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label314 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_center_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_center_type As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label216 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label216 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_DirAid_center control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_DirAid_center As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label215 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label215 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label313 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label313 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_center_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_center_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label169 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label169 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_current_disease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_current_disease As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label217 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label217 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_diseases_descr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_diseases_descr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dts_health_log control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_health_log As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grd_health_log control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_health_log As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dts_general_appearance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_general_appearance As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_disease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_disease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_surgery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_surgery As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_psych_state control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_psych_state As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_health_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_health_status As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_health_center_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_health_center_tab As Global.System.Web.UI.WebControls.SqlDataSource
End Class
