'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class orphans_supervisor_visits

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lnk_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_new As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_search As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_save As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_Delete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_Delete As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Literal1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Literal1 As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''lnk_search_rtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_search_rtn As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lnk_Get_Fayher_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnk_Get_Fayher_name As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lbl_visit_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_visit_no As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_visit_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_visit_no As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label265 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label265 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_supervisior_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_supervisior_name As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Label277 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label277 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_visit_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_visit_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label267 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label267 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_school_reg_date4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_school_reg_date4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label278 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label278 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_visit_notes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_visit_notes As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label279 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label279 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grd_visits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_visits As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dts_supervisior_visits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_supervisior_visits As Global.System.Web.UI.WebControls.SqlDataSource
End Class
