'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ReceiptCancellation

    '''<summary>
    '''ASPxLabel_MSG_Failure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_MSG_Failure As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxLabel_MSG_Success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_MSG_Success As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblDOnationCod0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod0 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxTextBox_reciept_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox_reciept_num As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxButton_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_New As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''Btn_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Btn_Search As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lblDOnationCod8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod8 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblDOnationCod1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''reciept_num_manual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reciept_num_manual As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod7 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''reciept_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reciept_date As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod2 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''donor_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donor_id As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod3 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''total_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents total_amount As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod4 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''currency_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_code As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod5 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''branch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents branch As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblDOnationCod6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOnationCod6 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''user_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents user_id As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxButton_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Save As Global.DevExpress.Web.ASPxButton
End Class
