'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCOrphanHobby

    '''<summary>
    '''HiddenField_app_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField_app_ser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''grd_hobby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_hobby As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''dts_hobby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_hobby As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_hobby_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_hobby_type As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dst_hobby_combo_main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dst_hobby_combo_main As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dts_hobby_combo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dts_hobby_combo As Global.System.Web.UI.WebControls.SqlDataSource
End Class
