'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCBeneficiaryScholarshipsV2

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''txt_app_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_app_ser As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_applicant_name_en control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_applicant_name_en As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label231 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label231 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_applicant_name_ar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_applicant_name_ar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label230 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label230 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''reasons_tab_DS4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS4 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS5 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS6 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''students_scholarship_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents students_scholarship_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''city_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents city_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS7 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''currency_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''pay_method_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pay_method_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''acad_year_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acad_year_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''org_type_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents org_type_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''stud_qualif_type_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stud_qualif_type_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''stud_qualif_level_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stud_qualif_level_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''stud_prof_types_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stud_prof_types_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''org_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents org_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS8 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS9 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS10 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''reasons_tab_DS11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reasons_tab_DS11 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_GetSchoolsByType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_GetSchoolsByType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''ASPxGridView4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView4 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_Select_students control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Select_students As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''LinqDS_Schools control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinqDS_Schools As Global.DevExpress.Data.Linq.LinqServerModeDataSource

    '''<summary>
    '''ASPxCallback1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback1 As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''LoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanel As Global.DevExpress.Web.ASPxLoadingPanel

    '''<summary>
    '''DS_Scholarship_patterns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Scholarship_patterns As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Scholarship_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Scholarship_status As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Scholarship_types control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Scholarship_types As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Education_Faculties_master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Education_Faculties_master As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ODS_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ODS_Status As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''ltrl_updatePeriod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrl_updatePeriod As Global.System.Web.UI.WebControls.Literal
End Class
