'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCSchoolsBasicInfoDetailsV1

    '''<summary>
    '''Label335 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label335 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label336 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label336 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''school_grades_GRD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_grades_GRD As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ASPxGridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView2 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''school_grades_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_grades_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''school_holidays_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_holidays_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''currency_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''acad_year_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acad_year_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''grades_setup_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grades_setup_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txt_school_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_school_code As Global.System.Web.UI.WebControls.TextBox
End Class
