'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCScholarshipExpensesV1

    '''<summary>
    '''ASPxGridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView2 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''fees_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fees_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''students_scholarship_fees_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents students_scholarship_fees_DS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
