'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCSchoolBuildingsV1

    '''<summary>
    '''Label337 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label337 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GRD_school_build control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GRD_school_build As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''txt_school_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_school_code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''school_building_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents school_building_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''acad_year_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acad_year_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''currency_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''unit_types_codes_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unit_types_codes_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''unit_cond_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unit_cond_DS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
