'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCProjectPhaseDetail

    '''<summary>
    '''ASPxPageControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPageControl1 As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''UCProjectPhasePhoto1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCProjectPhasePhoto1 As Global.DirectAid.UCProjectPhasePhoto

    '''<summary>
    '''UCProjectPhaseDocument1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCProjectPhaseDocument1 As Global.DirectAid.UCProjectPhaseDocument

    '''<summary>
    '''UCProjectPhaseNeed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCProjectPhaseNeed1 As Global.DirectAid.UCProjectPhaseNeed

    '''<summary>
    '''UCProjectPhaseTransfer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UCProjectPhaseTransfer1 As Global.DirectAid.UCProjectPhaseTransfer
End Class
