'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UCProject

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnManualProjectAllocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnManualProjectAllocation As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFind As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNum As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel3 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtNameAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameAR As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtRefNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefNum As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel4 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtNameEN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNameEN As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel33 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxLabel35 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel35 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel5 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''deApproveDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deApproveDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel6 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''deStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deStartDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel7 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''deFinishDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deFinishDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel8 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cboClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboClass As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel9 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''donation_cat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donation_cat As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel50 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel50 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''donation_value control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents donation_value As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel10 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cboNature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboNature As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel14 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboRelated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRelated As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel13 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboState As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel12 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboBenefit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboBenefit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel16 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboTarget As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel15 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboRequest As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel17 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel17 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel25 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel25 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCurrency As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel37 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel37 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_project_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_project_road As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel24 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel24 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtFurnishCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFurnishCost As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel32 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel32 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboFurnishCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFurnishCurrency As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel20 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel20 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_electricity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_electricity As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel21 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel21 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_water_avail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_water_avail As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel22 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel22 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_water_source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_water_source As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel38 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel38 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxComboBox_water_pump control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_water_pump As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel18 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel18 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBox_Area_Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_Area_Unit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel23 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel23 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtDepth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepth As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBox_Depth_Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_Depth_Unit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel19 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel19 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtCapacity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCapacity As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxComboBox_Capacity_Unit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxComboBox_Capacity_Unit As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel40 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel40 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''maintenance_start_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_start_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel41 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel41 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''maintenance_duration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maintenance_duration As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel42 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''geo_coordinates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents geo_coordinates As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel43 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''start_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents start_cost As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel44 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''over_reason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents over_reason As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''over_plan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents over_plan As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''ASPxLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel45 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ax_dimension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ax_dimension As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel46 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''loan_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loan_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel47 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''beneficiary_count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents beneficiary_count As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel48 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''loan_pay_period control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loan_pay_period As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel49 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''loan_pay_start_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loan_pay_start_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel11 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboFundSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboFundSource As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel26 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel26 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtSpecs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpecs As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''ASPxLabel34 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel34 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxLabel36 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel36 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxLabel27 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel27 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''nat_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nat_code As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel28 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel28 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cboGovernorate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboGovernorate As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel29 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel29 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cboCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCity As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel30 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel30 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cboCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cboCenter As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel31 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel31 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtVillageName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVillageName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel39 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel39 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''ASPxTextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxTextBox1 As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_Currency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_Currency As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''btnPhases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPhases As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemarks As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnResponsibles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResponsibles As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnLetters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLetters As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnDonors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDonors As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnCosts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCosts As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnRevenue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRevenue As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''btnFacility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFacility As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''SqlDataSource_Project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Project As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProjectType As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ProjectState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProjectState As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Organization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Organization As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_ProjectTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_ProjectTarget As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Currency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Currency As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Country As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Governorate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Governorate As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_City control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_City As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_Center control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_Center As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_GetNextID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_GetNextID As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_PROJECT_CLASS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_PROJECT_CLASS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_funding_source control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_funding_source As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlDataSource_unit_of_measure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource_unit_of_measure As Global.System.Web.UI.WebControls.SqlDataSource
End Class
