'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MedHR

    '''<summary>
    '''grd_ConvoysList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoysList As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_HR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_HR As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''job_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Countries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Countries As Global.System.Web.UI.WebControls.SqlDataSource
End Class
