'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MedicalInstitution

    '''<summary>
    '''grd_ConvoysList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoysList As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_medical_institutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_medical_institutions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_institution_types control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_institution_types As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_institution_nearby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_institution_nearby As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_institution_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_institution_status As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_institution_license control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_institution_license As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_institution_facilitation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_institution_facilitation As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Countries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Countries As Global.System.Web.UI.WebControls.SqlDataSource
End Class
