'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UIEvent

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ASPxButton_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_New As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Save As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxCallback_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback_Save As Global.DevExpress.Web.ASPxCallback

    '''<summary>
    '''ASPxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLoadingPanel1 As Global.DevExpress.Web.ASPxLoadingPanel

    '''<summary>
    '''ASPxLabel_app_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_id As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''Label227 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label227 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''event_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_type As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel_app_ser1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_name_ar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_name_ar As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser2 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_name_en control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_name_en As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser42 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser42 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_title control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_title As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser8 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_frm_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_frm_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_app_ser43 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser43 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_to_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_to_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_app_ser44 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser44 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''shifts_count control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents shifts_count As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser53 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser53 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_start_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_start_time As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_app_ser54 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser54 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_end_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_end_time As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''event_country control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_country As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel2 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''event_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_city As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ASPxLabel_app_ser45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser45 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_place control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_place As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser46 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser46 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''minimum_participants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents minimum_participants As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel45 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel45 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''event_cost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents event_cost As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''ASPxLabel_app_ser47 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser47 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''close_ceremony_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_ceremony_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_app_ser48 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser48 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''result_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents result_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxLabel_app_ser49 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel_app_ser49 As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''reward_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reward_date As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''ASPxButton_Accomodation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Accomodation As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Activities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Activities As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Committe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Committe As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Fees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Fees As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Groups control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Groups As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Participants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Participants As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Purposes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Purposes As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ASPxButton_Reasons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxButton_Reasons As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''EntityDataSource_nat_tab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_nat_tab As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EntityDataSource_event_types_codes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_event_types_codes As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''EntityDataSource_city control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EntityDataSource_city As Global.System.Web.UI.WebControls.EntityDataSource
End Class
