'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConvoyDetails

    '''<summary>
    '''grd_ConvoyObjectives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyObjectives As Global.DevExpress.Web.ASPxPageControl

    '''<summary>
    '''ContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl1 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyMembers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyMembers As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''job_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents job_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_convoy_members control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_members As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl2 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''ASPxGridView3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView3 As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_objectives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_objectives As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl3 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyActivities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyActivities As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_activities_master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_activities_master As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_convoy_activities control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_activities As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl4 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyResults As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_disease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_disease As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_convoy_results control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_results As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl5 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyMedicament control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyMedicament As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_medicines_and_supplies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_medicines_and_supplies As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_convoy_medecines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_medecines As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl6 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyExpenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyExpenses As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_expenses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_expenses As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl7 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoyAdvantages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoyAdvantages As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_advantages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_advantages As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl8 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoySuggestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoySuggestions As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_convoy_suggestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_convoy_suggestions As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ContentControl9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentControl9 As Global.DevExpress.Web.ContentControl

    '''<summary>
    '''grd_ConvoySpecialists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_ConvoySpecialists As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''DS_specialists_decision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_specialists_decision As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Expenses_Master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Expenses_Master As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''currency_tab_DS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents currency_tab_DS As Global.System.Web.UI.WebControls.SqlDataSource
End Class
